import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ReactFullpage from '@fullpage/react-fullpage';

export default function Home() {
  return (
    <div className={styles.Container}>
      <Head>
        <title>윤긍's page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ReactFullpage
        //fullpage options
        licenseKey={'YOUR_KEY_HERE'}
        scrollingSpeed={1000} /* Options here */

        render={({ state, fullpageApi }) => {
          return (
            <ReactFullpage.Wrapper>
              <div className="section">
                <div className={styles.main}>
                  <div className={styles.header}>
                    <div className={styles.route}>
                      <div onClick={() => fullpageApi.moveTo(2)}>About</div>
                      <div onClick={() => fullpageApi.moveTo(3)}>Work</div>
                      <div onClick={() => fullpageApi.moveTo(4)}>Contact</div>
                    </div>
                  </div>
                  <div className={styles.content}>
                    <div className={styles.title}>
                      Hi! I'm Developer,  "윤긍"
                    </div>
                    <div className={styles.text}>
                      <div>
                        안녕하세요! 상상하는 개발자, 윤긍입니다. <span>(MBTI ISTP인건 안비밀)</span> <br />
                        현재 한국디지털미디어고등학교에 재학중인 낭만있는 고등학생 2학년이고요! <br />
                        다양한 분야에서 활약할 수 있는 인재가 되기 위해 끊임없이 노력하고 있습니다! <br />
                        이 초라한 곳에 찾아와주신것에 대단히 감사하고요, <br />이제부터 저에 대해 하나씩 알아가는 시간 가져보도록 할게요! <br />
                        Hello! I'm Imagining Developer dandan. <br />
                        Um.... Eng is so difficult hahaha... <br />
                        So... just Fllow me!!
                      </div>
                    </div>
                    <div className={styles.bottom}>
                      <div className={styles.button} onClick={() => fullpageApi.moveTo(2)}>Follow</div>
                      <div className={styles.arrow} onClick={() => fullpageApi.moveTo(2)}><i class="material-icons">arrow_downward</i></div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="section">
                <div className={styles.section1}>
                  <div className={styles.section1_left_side}>
                    d
                  </div>
                  <div className={styles.section1_middle_side}>
                    <div className={styles.profile}>
                      <img src="https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg" width="320px" height="320px" alt="" />
                    </div>
                  </div>
                  <div className={styles.section1_right_side}>
                    d
                  </div>
                </div>
              </div>
              <div className="section">
                setcion2
              </div>
              <div className="section">
                setcion3
              </div>
            </ReactFullpage.Wrapper>
          );
        }}
      />

    </div>
  )
}
