import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ReactFullpage from '@fullpage/react-fullpage';

export default function Home() {
  return (
    <div className={styles.Container}>
      <Head>
        <title>{`윤긍's page`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ReactFullpage
        //fullpage options
        licenseKey={'YOUR_KEY_HERE'}
        scrollingSpeed={1000} /* Options here */

        render={({ state, fullpageApi }) => {
          return (
            <ReactFullpage.Wrapper>
              <div className="section">
                <div className={styles.main}>
                  <div className={styles.header}>
                    <div className={styles.route}>
                      <div onClick={() => fullpageApi.moveTo(2)}>{`About`}</div>
                      <div onClick={() => fullpageApi.moveTo(3)}>{`Work`}</div>
                      <div onClick={() => fullpageApi.moveTo(4)}>{`Contact`}</div>
                    </div>
                  </div>
                  <div className={styles.content}>
                    <div className={styles.title}>
                      {`Hi! I'm Developer,  "윤긍"`}
                    </div>
                    <div className={styles.text}>
                      <div>
                        {`안녕하세요! 상상하는 개발자, 윤긍입니다.`} <br />
                        {`현재 한국디지털미디어고등학교에 재학중인 2학년 학생입니다. `} <br />
                        {`다양한 분야에서 인정받는 사람이 될 수 있도록 노력하고있습니다. `} <br />
                      </div>
                    </div>
                    <div className={styles.bottom}>
                      <div className={styles.button} onClick={() => fullpageApi.moveTo(2)}>{`Follow`}</div>
                      <div className={styles.arrow} onClick={() => fullpageApi.moveTo(2)}><i className="material-icons">{`arrow_downward`}</i></div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="section">
                <div className={styles.about}>
                  <div className={styles.title}>
                    {`About Me`}
                  </div>
                  <br />
                  <div className={styles.row}>
                    <div className={styles.content}>
                      <div className={styles.name}>
                        <span>Name</span>
                      </div>
                      <div className={styles.value}>
                        <span>김은교</span>
                      </div>
                    </div>
                    <div className={styles.content}>
                      <div className={styles.name}>
                        <span>Birth</span>
                      </div>
                      <div className={styles.value}>
                        <span>2005/02/20</span>
                      </div>
                    </div>
                    <div className={styles.content}>
                      <div className={styles.name}>
                        <span>School</span>
                      </div>
                      <div className={styles.value}>
                        <span className={styles.schools}>
                          한국디지털미디어고등학교
                        </span>
                      </div>
                    </div>
                  </div>
                  <br /><br />
                  <div className={styles.row}>
                    <div className={styles.content}>
                      <div className={styles.name}>
                        <span>Tel</span>
                      </div>
                      <div className={styles.value}>
                        <span>010-4580-5306</span>
                      </div>
                    </div>
                    <div className={styles.content}>
                      <div className={styles.name}>
                        <span>Email</span>
                      </div>
                      <div className={styles.value}>
                        <span>2005/02/20</span>
                      </div>
                    </div>
                    <div className={styles.content}>
                      <div className={styles.name}>
                        <span>Location</span>
                      </div>
                      <div className={styles.value}>
                        <span>안산시 상록구</span>
                      </div>
                    </div>

                  </div>
                </div>
              </div>
              <div className="section">
              </div>
              <div className="section">
              </div>
            </ReactFullpage.Wrapper>
          );
        }}
      />

    </div>
  )
}
